version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      # デバッグ用
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - db